package com.guarani.siuguarani.enums;

public enum MateriasEnum {
    ANALISIS_MATEMATICO_I,
    LOGICA_SIMBOLICA,
    TEORIA_DE_GRAFOS_Y_ALGORITMIA,
    TALLER_DE_PROGRAMACION_I,
    INGLES_TECNICO_I,
    
    ANALISIS_MATEMATICO_II,
    ALGORITMOS_Y_ESTRUCTURAS_DE_DATOS_I,
    ARQUITECTURA_DE_LAS_COMPUTADORAS_I,
    TALLER_DE_PROGRAMACION_II,
    INGLES_TECNICO_II,
    
    ALGORITMOS_Y_ESTRUCTURAS_DE_DATOS_II,
    DISENO_ORIENTADO_A_OBJETOS,
    BASES_DE_DATOS,
    PROBABILIDAD_Y_ESTADISTICA,
    ARQUITECTURA_DE_LAS_COMPUTADORAS_II,
    
    SISTEMAS_OPERATIVOS,
    REDES_DE_COMPUTADORAS_I,
    TALLER_DE_PROGRAMACION_III,
    TEORIA_DE_LENGUAJES,
    
    PASANTIA_EXTERNA,
    SEGURIDAD_INFORMATICA,
    REDES_DE_COMPUTADORAS_II,
    INGENIERIA_DE_SOFTWARE_I,
    TALLER_DE_PROGRAMACION_IV,
    
    INGENIERIA_DE_SOFTWARE_II,
    GESTION_DE_LAS_ORGANIZACIONES,
    PROGRAMACION_PROFESIONAL,
    SEMINARIO_I,
    SEMINARIO_II,
    SEMINARIO_III
}
